- name: Massages
  hosts: mail, yandex
  become: yes

  vars:
    slovo1: DOM
    slovo2: in
    mesto: RUS


  tasks:

  - name: Print Vars
    debug:
      var: slovo1

    debug:
      msg: "Moj dom v {{mesto}}"

    debug:
      msg: "Moj {{slovo1}} {{slovo2}} {{mesto}}" 


  - set_fact:
      message: "Moj {{slovo1}} {{slovo2}} {{mesto}}" 

  - debug: 
      var: message   
# запрашиваем в каких групах состоит пользователь
  - shell: id dus0182
    register: clirnt_groups

  - debug:
      msg: "dus0182 in Groups: {{clirnt_groups}}"    